#!/bin/sh
location=0
headerlenght=2
getsource(){
	cat $source
}
location(){
	add=$1
	location=$(expr $location + $add )
}
getpart(){
	tailcut=$1
	headcut=$2
	getsource | head -c $headcut | tail -c $(expr $headcut - $tailcut )
}
unpack(){
	source=$1
	if [ -z $2 ]; then
		output=$PWD
	else
		mkdir $2
		output=$2
	fi
	sizepointer=$(getpart 0 $headerlenght)
	location $headerlenght
	while [ $location -lt $(getsource | wc -c ) ]
	do
		size=$( getpart $location $(expr $location + $sizepointer))
		location $sizepointer
		title=$(getpart $location $(expr $location + $size))
		location $size
		size=$( getpart $location $(expr $location + $sizepointer))
		location $sizepointer
		getpart $location $(expr $location + $size) > $output/$title
		echo unpacking file $title
		location $size
	done
	cd $output
	for item in $(ls)
	do
		if [ "${item##*.}" = ldar ]; then
			location=0
			unpack "$item" "${item%.*}"
			echo unpacking folder "${item%.*}" as defined by "$item"
			cd ..
		fi
	done
	rm *.ldar
}
max(){
	echo finding largest file...
	max=0
	for file in $(find -type f)
	do
		tmp=$(cat $file | wc -c)
		if [ ! $max -gt $tmp ]; then
			max=$tmp
		fi
	done
	maxlenght=$(echo $max | wc -c)
}
###
rpack(){
	echo packing $1
	folder="$1"
	foldername=$(basename $folder)
	name=$foldername.ldar
	cd $folder
	for item in $(ls)
	do
		if [ -d $item ]; then
			rpack $item
			cd ..
		fi
	done
	folder="$1"
	foldername=$(basename $folder)
	name=$foldername.ldar
	max
	if [ ! $(expr $(echo $maxlenght | wc -c) - 1) = 2 ]; then
		sizepointer=0$maxlenght
	else
		sizepointer=$maxlenght
	fi
	echo -n $sizepointer >> ../$name
	for item in $(ls)
	do
		echo adding $item
		if [ -f $item ]; then
			itemnamelenght=$(echo -n $item | wc -c)
			until [ $(echo -n $itemnamelenght | wc -c ) = $maxlenght ]
			do
				itemnamelenght=0$itemnamelenght
			done
			echo -n $itemnamelenght >> ../$name
			echo -n $item >> ../$name
			contentlenght=$(cat $item | wc -c)
			until [ $(echo -n $contentlenght | wc -c ) = $maxlenght ]
			do
				contentlenght=0$contentlenght
			done
			echo -n $contentlenght >> ../$name
			cat $item >> ../$name
		fi
	done
}
pack(){
	current=$(realpath $PWD)
	if [ ! -d /tmp/ldar ]; then
		mkdir /tmp/ldar
	fi
	cp -r $1 /tmp/ldar/
	cd /tmp/ldar/
	rpack $1
	mv /tmp/ldar/"$1.ldar" $current
	rm -r /tmp/ldar
}
case "$1" in
	pack|unpack) $@;;
	*) echo "ldar: usage: ldar [ pack | unpack ] file...";;
esac
