#!/bin/sh
location=0
headerlenght=1
getsource(){
	cat $source
}
location(){
	add=$1
	location=$(expr $location + $add )
}
getpart(){
	tailcut=$1
	headcut=$2
	getsource | head -c $headcut | tail -c $(expr $headcut - $tailcut )
}
unpack(){
	source=$1
	if [ -z $2 ]; then
		output=$PWD
	else
		mkdir $2
		output=$2
	fi
	sizepointer=$(getpart 0 $headerlenght)
	location 1
	while [ $location -lt $(getsource | wc -c ) ]
	do
		size=$( getpart $location $(expr $location + $sizepointer))
		location $sizepointer
		title=$(getpart $location $(expr $location + $size))
		location $size
		size=$( getpart $location $(expr $location + $sizepointer))
		location $sizepointer
		getpart $location $(expr $location + $size) > $output/$title
		location $size
	done
	cd $output
	for item in $(ls)
	if [ "${item##*.}" = ldar ]; then
		unpack "$item" "${item%.*}"
		cd ..
	fi
		
}
###
pack(){
	folder="$1"
	foder=$(realpath $folder)
	foldername=$(basename $folder)
	name=$foldername.ldar
	cd $folder
	echo -n 9 >> ../$name
	for item in $(ls)
	do
		if [ -d $item ]; then
			pack $item
			cd ..
		fi
	done
	folder="$1"
	foder=$(realpath $folder)
	foldername=$(basename $folder)
	name=$foldername.ldar
	for item in $(ls)
	do
		if [ -f $item ]; then
			itemnamelenght=$(echo -n $item | wc -c)
			until [ $(echo -n $itemnamelenght | wc -c ) = 9 ]
			do
				itemnamelenght=0$itemnamelenght
			done
			echo -n $itemnamelenght >> ../$name
			echo -n $item >> ../$name
			contentlenght=$(cat $item | wc -c)
			until [ $(echo -n $contentlenght | wc -c ) = 9 ]
			do
				contentlenght=0$contentlenght
			done
			echo -n $contentlenght >> ../$name
			cat $item >> ../$name
		fi
	done
}
$@
